### ISSUE TITLE
Building with other than BLAS/LAPACK netlib

### ISSUE THREAD

**Issue by zerothi** [symPACK/symPACK#2]
The documentation does not specify that BLAS/LAPACK is necessary?

Is it, or is it not? The cmake files contain references to `BLAS_DIR` and `LAPACK_DIR` and so how is the recommended way in this setup? 

Also, how if I am going to use MKL/OpenBLAS/flame/atlas? How should I change accordingly?

Lastly, is BLAS+LAPACK only used for testing or is it actually merged into the library?

**Comment by mjacquel** [comment]
Hi @zerothi ,

BLAS / LAPACK are required because symPACK uses GEMM, TRSM and POTRF routines (among others), but it is NOT restricted to the netlib version.
 
In order to use OpenBLAS, you can set these variables to where OpenBLAS is located.
In order to use MKL, if you are using the Intel compiler, you can use the -mkl compiler flag together with the -ENABLE_MKL=ON cmake option (before configuring the project).

I can help you with setting up these variables if you like.

**Comment by zerothi** [comment]
In which env-vars should these be set? This is basically what I have my doubts on?

I.e. I may have openblas compiled with OpenMP and have a non-standard object name `libopenblas_omp`, will `BLAS_DIR=<openblas-prefix>` work?

**Comment by mjacquel** [comment]
Is it compiled as a static library? These variables are usually defined in
a toolchain file (you have some examples in the toolchains folder).

I think they can also be passed to cmake by using:
cmake ... -DBLAS_DIR=... ....

**Comment by mjacquel** [comment]
Dear Nick,

Have you been able to resolve your issue?

Best,

Mathias Jacquelin
Research Scientist
Lawrence Berkeley National Laboratory
mjacquelin@lbl.gov
1-510-495-2605

**Comment by zerothi** [comment]
Dear Mathias,

Sorry, I have been busy, but I haven't forgotten!
I'll be back once I get a hold of everything ;)

thanks!

**Comment by zerothi** [comment]
First run:

```bash
cmake -DCMAKE_INSTALL_PREFIX=/opt/gnu/8.3.0/sympack/1.1 -DMETIS_DIR=/opt/gnu/8.3.0/metis/5.1.0 -DENABLE_METIS=ON -DPARMETIS_DIR=/opt/gnu/8.3.0/parmetis/4.0.3 -DENABLE_PARMETIS=ON -DSCOTCH_DIR=/opt/gnu/8.3.0/scotch/6.0.4 -DENABLE_SCOTCH=ON -DCMAKE_BUILD_TYPE=Release -DBLAS_DIR=/opt/gnu/8.3.0/openblas/0.3.5 -DLAPACK_DIR=/opt/gnu/8.3.0/openblas/0.3.5 ..

... <lots of output>

-- Could NOT find BLAS (missing: BLAS_LIBRARIES) 
CMake Warning at CMakeLists.txt:108 (message):
  Warning: could not find a BLAS library


-- Could NOT find Threads (missing: Threads_FOUND) 
-- Could NOT find BLAS (missing: BLAS_LIBRARIES) 
-- LAPACK requires BLAS
-- A library with LAPACK API not found. Please specify library location.
CMake Warning at CMakeLists.txt:117 (message):
  Warning: could not find a LAPACK library


-- Performing Test METIS_TEST_RUNS
-- Performing Test METIS_TEST_RUNS - Failed
CMake Error at /opt/generic/build-tools/1.0/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find METIS (missing: METIS_TEST_RUNS)
Call Stack (most recent call first):
  /opt/generic/build-tools/1.0/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindMETIS.cmake:116 (find_package_handle_standard_args)
  CMakeLists.txt:177 (find_package)
```

So this makes me think I can do:
```bash
cmake -DCMAKE_INSTALL_PREFIX=/opt/gnu/8.3.0/sympack/1.1 -DMETIS_DIR=/opt/gnu/8.3.0/metis/5.1.0 -DENABLE_METIS=ON -DPARMETIS_DIR=/opt/gnu/8.3.0/parmetis/4.0.3 -DENABLE_PARMETIS=ON -DSCOTCH_DIR=/opt/gnu/8.3.0/scotch/6.0.4 -DENABLE_SCOTCH=ON -DCMAKE_BUILD_TYPE=Release -DBLAS_LIBRARIES=' -L/opt/gnu/8.3.0/openblas/0.3.5/lib -Wl,-rpath=/opt/gnu/8.3.0/openblas/0.3.5/lib -lopenblas' -DLAPACK_DIR=/opt/gnu/8.3.0/openblas/0.3.5 ..
```

But this gives this error:
```bash
-- A library with LAPACK API not found. Please specify library location.
CMake Warning at CMakeLists.txt:117 (message):
  Warning: could not find a LAPACK library
```
So there is something going on with LAPACK etc?

**Comment by zerothi** [comment]
Ok, you can override with `LAPACK_LIBRARIES` as well (it just does not inform of this) :)

**Comment by zerothi** [comment]
Closing this issues as it would be recommended for users to use `BLAS_LIBRARIES` and `LAPACK_LIBRARIES`.

:)
